### ISSUE TITLE
Sort 'related' according to importance

### ISSUE THREAD

**Issue by michel-kraemer** [radekstepan/metalsmith-related#2]
Pretty good library. I was just about to write something like this myself but then I discovered your project. Thanks!

I'm wondering if `related` should be sorted according to the document's importance. `TfIdf.tfidfs` returns an array sorted by document ID but not by importance so your plugin will always only return the first 5 documents instead of the first 5 most important documents.

Unfortunately I don't know coffescript. Otherwise I would have submitted a PR.

Cheers,
Michel

**Comment by michel-kraemer** [comment]
Thanks for merging the PR and for fixing this issue so quickly!

Could it be the posts are now sorted from lowest frequency to highest? This would mean `related` will contain the 5 least important documents and not the most important ones. Maybe I'm mistaken, because I don't understand the Coffeescript code completely, but you should probably check this.

Cheers,
Michel

**Comment by radekstepan** [comment]
You are absolutely right, well spotted Michel.

So (from tests):

`this document is about node` has these two as related in order:

1. `this document is about node. it has node examples`
1. `this document is about ruby and node`

**Comment by michel-kraemer** [comment]
Wow. This was really quick! Thanks a lot! :-) I tested the new version on the website I'm currently working on and it works very well.

Cheers,
Michel
